# Generated by Django 2.1 on 2018-08-25 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('uniqueAnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('uniqueUserID', models.TextField(max_length=200)),
                ('user_name', models.CharField(default='Anonymous', max_length=150)),
                ('user_location', models.CharField(max_length=200)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='issue date')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.TextField(default='Anonymous Organization', max_length=1000)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='OtherQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Random Question', max_length=1000)),
                ('question_type', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerMapping',
            fields=[
                ('uniqueUserAnswerMappingID', models.AutoField(primary_key=True, serialize=False)),
                ('uniqueQuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymousReporting.OtherQuestions')),
                ('uniqueUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymousReporting.Answers')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymousReporting.Authority'),
        ),
    ]
