# Generated by Django 2.1 on 2018-08-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymousReporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherquestions',
            name='isRequired',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='authority',
            name='authority_name',
            field=models.CharField(default='Anonymous Organization', max_length=1000),
        ),
    ]
