# Generated by Django 2.1 on 2018-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymousReporting', '0002_auto_20180825_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswermapping',
            name='answer',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
