# Generated by Django 2.1 on 2018-08-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymousReporting', '0004_auto_20180825_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswermapping',
            name='uniqueAnswerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anonymousReporting.Answers'),
            preserve_default=False,
        ),
    ]
