# Generated by Django 2.1 on 2018-08-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymousReporting', '0005_useranswermapping_uniqueanswerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswermapping',
            name='uniqueAnswerID',
        ),
    ]
