# Generated by Django 2.1 on 2018-08-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymousReporting', '0006_remove_useranswermapping_uniqueanswerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswermapping',
            name='uniqueAnswerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anonymousReporting.Answers'),
        ),
    ]
